### PR TITLE
Support for fine-tuning Llama 3.1 Omni.

### PR DESCRIPTION
**Pull request by Jintao-Huang**
model: https://modelscope.cn/models/ICTNLP/Llama-3.1-8B-Omni

github: https://github.com/ictnlp/LLaMA-Omni

### CODE REVIEW

**Comment by Jintao-Huang** [comment]
https://github.com/ictnlp/LLaMA-Omni/issues/1

**Comment by Jintao-Huang** [comment]
inference
```bash
CUDA_VISIBLE_DEVICES=0 swift infer --model_type llama3_1-8b-omni
```

sft
```bash
NPROC_PER_NODE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft --model_type llama3_1-8b-omni --dataset aishell1-zh-mini#20000 --deepspeed default-zero2 --sft_type lora --output_dir output
```

**Review by tastelikefeet — APPROVED** [review]

**Comment by satheeshkola-532** [comment]
> inference
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0 swift infer --model_type llama3_1-8b-omni
> ```
> 
> sft
> 
> ```shell
> NPROC_PER_NODE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft --model_type llama3_1-8b-omni --dataset aishell1-zh-mini#20000 --deepspeed default-zero2 --sft_type lora --output_dir output
> ```

hey @Jintao-Huang , i have fine tuned the llama omni by using the custom instruction dataset on another language using the above given cli command, it is generating the promising text responses in the desired language, but the audio generated is not supporting the desired lanugage(means vocoder isn't generating audio in fine tuned lanugae), so could you please check this issue once to completely fine tune the entire pipeline?

**Comment by fromlimbo** [comment]
@Jintao-Huang 你好，我在A800上面CUDA_VISIBLE_DEVICES=0是可以正常sft的，改成CUDA_VISIBLE_DEVICES=0，1多卡就会报错NotImplementedError: Cannot copy out of meta tensor; no data!
，请问是不支持吗？
`CUDA_VISIBLE_DEVICES=0 swift sft \
  --model_type llama3_1-8b-omni \
  --model_id_or_path ICTNLP/Llama-3.1-8B-Omni \
  --sft_type lora \
  --dataset aishell1-zh-mini#5000
`

**Comment by ParikshitGehlaut** [comment]
Does anyone facing issue with hugging face accelerate version ? latest version is 1.0.1, But I getting error that data_seed requires  Accelerate version `accelerate` >= 1.1.0.

**Comment by kadirnar** [comment]
@Jintao-Huang ,

I have never used the Swift library. I will try it for the first time. I want to train the Llama-Omni model from scratch. I want to use Llama3.3 70B and whisper large v3 model. Is this possible?

**Pull request merged**
